// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlJwzvaKVDwinZ7Yoyeylr4WpS66rJzX8',
    appId: '1:701741613219:web:e8d4965554aa696bfd7f16',
    messagingSenderId: '701741613219',
    projectId: 'kapallawd-70c45',
    authDomain: 'kapallawd-70c45.firebaseapp.com',
    storageBucket: 'kapallawd-70c45.firebasestorage.app',
    measurementId: 'G-09J031WJH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmabvmeF2IDKOmLOYcvUWk4BFnxmTmbGI',
    appId: '1:701741613219:android:b40914c0b4868dd4fd7f16',
    messagingSenderId: '701741613219',
    projectId: 'kapallawd-70c45',
    storageBucket: 'kapallawd-70c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeP_yn_TTh5eLvh9fnhjkIwqgT2WH8rTA',
    appId: '1:701741613219:ios:a688547f5e1fff83fd7f16',
    messagingSenderId: '701741613219',
    projectId: 'kapallawd-70c45',
    storageBucket: 'kapallawd-70c45.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeP_yn_TTh5eLvh9fnhjkIwqgT2WH8rTA',
    appId: '1:701741613219:ios:a688547f5e1fff83fd7f16',
    messagingSenderId: '701741613219',
    projectId: 'kapallawd-70c45',
    storageBucket: 'kapallawd-70c45.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlJwzvaKVDwinZ7Yoyeylr4WpS66rJzX8',
    appId: '1:701741613219:web:5ad9b6d22798d50ffd7f16',
    messagingSenderId: '701741613219',
    projectId: 'kapallawd-70c45',
    authDomain: 'kapallawd-70c45.firebaseapp.com',
    storageBucket: 'kapallawd-70c45.firebasestorage.app',
    measurementId: 'G-VPGFZD474W',
  );
}
